// src/services/quickActions.js
// Pre-programmed life events that modify multiple attributes at once

export const quickActions = [
  {
    id: 'Job1',
    label: '💼 補習',
    room: 'Room Z210',
    requirements: { wisdom: 3 }, // Admin checks manually
    effects: { money: +200, energy: -2, sanity: -1 },
    announcement: '',
  },
  {
    id: 'Job2',
    label: '💼 Food Panda',
    room: 'Room Z210',
    requirements: { strength: 3 }, // Admin checks manually
    effects: { money: +170, energy: -3, sanity: -2, social: -1 },
    announcement: '',
  },
  {
    id: 'Job3',
    label: '💼 摺衫',
    room: 'Room Z210',
    requirements: { },
    effects: { strength: +1, social: -1, energy: -1, money: +20 },
    announcement: '',
  },
  {
    id: 'Study1',
    label: '📚 通霄摺liba',
    room: 'Room Z210',
    requirements: { },
    effects: { wisdom: +3, sanity: -4, energy: -3, strength: -1 },
    announcement: 'Player X 📚 通霄摺liba! 😱',
  },
  {
    id: 'Study2',
    label: '📚 讀自去偷歡(kahoot)',
    room: 'Room Z210',
    requirements: { wisdom: 5 },
    effects: { wisdom: +2, energy: -2, sanity: -3 },
    announcement: '',
  },
  {
    id: 'InterestClub',
    label: '🎉 上莊',
    room: 'Room Z208',
    requirements: { },
    effects: { social: +2, energy: -5, sanity: -2 },
    announcement: '',
  },
  {
    id: 'Love1',
    label: '❤️ 交友app',
    room: 'Room Z210',
    requirements: { },
    effects: { sanity: +1, social: +1, energy: -1, strength: -1 },
    announcement: '',
  },
  {
    id: 'Love2',
    label: '❤️ 愛裏沒有懼怕',
    room: 'Room Z210',
    requirements: {social: 5},
    effects: { social: +3, sanity: +3, energy: -8, money: -200 },
    announcement: '',
  },
  {
    id: 'Hallgame1',
    label: '🏠 背金句',
    room: 'Room Z208',
    requirements: { },
    effects: { sanity: -1, social: +1, energy: -1, money: -20 },
    announcement: '',
  },
  {
    id: 'Hallgame2',
    label: '🏠 拍7',
    room: 'Room Z208',
    requirements: { },
    effects: { sanity: +1, social: +2, energy: -3, money: -20 },
    announcement: '',
  },
  {
    id: 'coffee',
    label: '☕ coffee',
    room: 'Shop (Z210)',
    requirements: { },
    effects: { energy: +3, money: -10 },
    announcement: '',
  },
  {
    id: 'red bull',
    label: '🍺 red bull',
    room: 'Shop (Z210)',
    requirements: { },
    effects: { energy: +7, money: -20 },
    announcement: '',
  },
 {
    id: 'resting',
    label: '🛌 休息室',
    room: 'Z506',
    requirements: { },
    effects: { },
    announcement: '',
  },
];